### ISSUE TITLE
Reset All may lead to repeated and miscounted levels

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#112]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/761.
If you leave a level after getting it right but before seeing the next one, and then use reset all, then re-entering that game will show you the previously beaten level and beating it will not count toward your new score.

**Steps to reproduce**
1. Go to the top left game
2. Beat the first level but do not click the next button
3. Go back to the game select screen
4. Reset all
5. Enter the top left game again
6. Beat the first level again (note it is the same as before)
7. Observe score

**Visuals**
![resetall](https://user-images.githubusercontent.com/41024075/148841329-7937af29-8b41-4f7d-946a-dc9a89f1957c.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.35/phet/number-play_all_phet.html?screens=4
Version: 1.0.0-dev.35 2022-01-10 18:25:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
I also noted that, if you hit reset all before answering, the new starting level will have the same answer as the level you reset. If this is the first level then the depiction of the number doesn't even change.

**Comment by KatieWoe** [comment]
It also seems to only impact the top two games.

**Comment by chrisklus** [comment]
Nice find @KatieWoe! What you demonstrated is the only way to play the game without triggering a "new challenge", which fires when the play button (on the subitize game) or next button (on both games) is pressed. The counting games are setup and start running just from the instantiation of the screen.

@Luisav1 and I fixed by setting a random value for the play object type and challenge number on `reset()`, and also resetting the number of button presses (previously just reset from a "new challenge").

Ready to test on master and close if all looks good. Thanks!

**Comment by KatieWoe** [comment]
Looks good on master
