### ISSUE TITLE
Numbers/comparison statements not read out on ChromeOS

### ISSUE THREAD

**Issue by stemilymill** [phetsims/number-play#138]
Chromebook version 97.0.4692.102 (32-bit)
For https://github.com/phetsims/qa/issues/771

When I click the speech button to read out the number or the comparison statement (screen 3), the sound for the button click is played but the number is not read out. 

Note: after I noticed this, I updated the OS/browser, and then the number was read out twice. Then when I switched screens it did not work anymore. 

https://user-images.githubusercontent.com/85511101/152278342-da567bad-f715-413e-b3cf-b31ead672ec1.mp4

<details><summary>Troubleshooting information:</summary><p>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.45/phet/number-play_all_phet.html?screens=1,2,3
Version: 1.0.0-dev.45 2022-01-31 11:53:19 UTC
Features missing: applicationcache, csstransforms3d, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (X11; CrOS aarch64 14324.80.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.102 Safari/537.36
Language: en-US
Window: 1300x629
Pixel Ratio: 1.0499999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 96)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}
</p></details>

**Comment by chrisklus** [comment]
Thanks @stemilymill! Would you mind checking if there's any console errors?

**Comment by stemilymill** [comment]
@chrisklus Here is all that shows up in console:

﻿
number-play_all_phet…l?screens=1,2,3:894 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
number-play_all_phet…l?screens=1,2,3:894 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
number-play_all_phet.html:894 [Violation] 'setTimeout' handler took 454ms
number-play_all_phet.html:894 [Violation] 'setTimeout' handler took 321ms
number-play_all_phet.html:894 [Violation] 'setTimeout' handler took 266ms
number-play_all_phet.html:894 [Violation] 'setTimeout' handler took 287ms
[Violation] 'requestAnimationFrame' handler took 160ms
﻿
​

**Comment by chrisklus** [comment]
Awesome thanks - one more question, and then it might be best to setup a zoom meeting at some point since I don't have a ChromeOS device. Can you operate the sim with the dev tools open and see if those ` 'setTimeout' handler took` errors correspond with pressing the speech button?

**Comment by stemilymill** [comment]
All of those pop up as the sim loads, before I even click into a screen from the home screen

**Comment by chrisklus** [comment]
Got it, thank you

**Comment by chrisklus** [comment]
When meeting with @jessegreenberg, he mentioned that he has a Chromebook that he could take a look with, thanks!

**Comment by jessegreenberg** [comment]
So I just saw something pretty strange. I was testing https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.45/phet/number-play_all_phet.html?screens=1,2,3 on my chromebook. At first no speech synthesis worked. So then I went to test number-play master and still no speech synthesis worked. Then I went to test published john-travoltage. When I got to the sim I heard lots of numbers from number-play, even though john-travoltage was loaded. Then I started hearing john-travoltage Voicing.

After that, all speech synthesis in number play was working as expected in the dev version and in master. I tried restarting the chromebook and chrome to get the problem to happen again, but haven't been able to since.

**Comment by jessegreenberg** [comment]
I switched tabs to search for how to find my chromebook model. When I returned to the sim, all speech synthesis is muted.

**Comment by jessegreenberg** [comment]
OK, I found a consistent way to break it.
1) Load the sim and press the button or use ?countAloud to hear voicing.
2) Switch tabs to a sim that does NOT use speech synthesis and stay on that tab for ~30 seconds.
3) Come back to the sim and try to use speech synthesis, it will be broken.

**Comment by jessegreenberg** [comment]
I logged these things around the ENGINE_WAKE_INTERVAL of SpeechSynthesisAnnouncer:
console.log( this.getSynth().speaking, queue.length, this.timeSinceWakingEngine );

I am finding that when speech synthesis is broken, `this.getSynth().speaking` is always **true**!!

**Comment by jessegreenberg** [comment]
I was able to produce this in a case outside of a PhET sim: https://codepen.io/matt-west/pen/DpmMgE

**Comment by jessegreenberg** [comment]
I was able to produce the bug in this basic HTML example

<details>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>TEST PAGE</title>
  </head>
  <body>

  <button id="button">Press me!</button>
  </body>

<script>
  document.getElementById( 'button' ).addEventListener( 'click', () => {
    window.speechSynthesis.speak( new SpeechSynthesisUtterance( 'You just pressed me!' ) );
  } );
</script>
</html>
```

</details>

**Comment by jessegreenberg** [comment]
I am about ready to throw in the towel here. Ill check in with the team to request assistance or see if  we should reconsider supporting voicing on Chromebooks. I have identified that this is a Chromebook bug and reproduced the issue in a basic HTML5 example. At the very least we should submit a bug report to google.

**Comment by chrisklus** [comment]
@jessegreenberg thank you so much for investigating! That is super weird behavior. Let me know I could be helpful at all to pair to continue brainstorming ideas.

**Comment by chrisklus** [comment]
From design meeting:

We are okay to publish to the prototype with this issue, and would add a note in the teacher tips. @kathy-phet asked QA to check other published sims with voicing on ChromeOS.

@jessegreenberg do you think the thought in your last comment is worth investigating still?

**Comment by jessegreenberg** [comment]
Yes, sorry I haven't gotten to it yet. Regarding other published sims, I fully expect this to be an issue for them as well since I was able to observe this outside of a PhET sim.

**Comment by KatieWoe** [comment]
From what I saw on the Chromebook in the office:
Number play on master: The speaker button didn't seem to work at first. Switch tabs and coming back seemed to fix it.
John Travoltage published: Voicing worked for the most part. Switching to a different tab for a minute and coming back stopped voicing until pressing one of the description buttons, then it came back. Otherwise seemed normal from a quick check. It may have skipped the first "Voicing on" dialog, but everything after seemed to play.
Gravity Force Lab Basics published: Same as John Travoltage.

**Comment by Nancy-Salpepi** [comment]
@jessegreenberg I was testing published JT and GFL:B on Chromebook this morning and voicing was working. 
With chromeOS 98 I noticed delays in 3 instances:
1. When voicing is initially turned on: I don't hear anything after pressing the toggle button. It doesn't come on until after I tab through a few things.
2. After switching to another tab and then returning (see video)
3. After leaving the sim open for a while and then tabbing or clicking on things. 

https://user-images.githubusercontent.com/87318828/153636627-5142250b-3465-471d-a22b-38138521ef8b.mov

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe and @Nancy-Salpepi! This is very helpful to know.

**Comment by zepumph** [comment]
@jessegreenberg briefed me on this issue today during a11y-team dev meeting, and I had a large number of thoughts about how to pursue this issue. The vast majority of them have already been tried by @jessegreenberg, but I felt like applying a bit more rigor to the potential cross-product of possible solutions may be our best bet in finding a workaround.

First off, @jessegreenberg and I thought about the prospect of giving up on supporting Chromebook (as stated in https://github.com/phetsims/number-play/issues/138#issuecomment-1032885116). I support you @jessegreenberg!! I was also curious if we could just let this bug be, report it to google, and still consider ourselves "supporting chromebook". @jessegreenberg mentioned that this bug really looks like our fault, and so it wouldn't be that good a situation to have it break in the wild.

Next, I feel like workaround will need to consist of three separate parts, that all may be related, and may need some cross-product testing to see what works best.

1. Detection of the error case. 
  i. @jessegreenberg mentioned in   https://github.com/phetsims/number-play/issues/138#issuecomment-1032885116 that we can time the space between calling speak and receiving a `start` event, if too long, then do something to fix it.
  ii. In `step` each frame, test to see if it has been too long before we got a `start` event.
  iii. We could listen to the browser-tab-visible Property and either check the timing above, or just assume that any time on another tab is long enough to potentially break this stuff. 
2. Placement of the fix:
  i. I mentioned to @jessegreenberg that it seemed like most of the testing he was doing was around the `speak` that is the chromebook kickstart empty `speak`. This is likely important to do!
  ii. In addition, I feel like we can't forget about the actual call to `speak` with content, because that would be the buggiest case to handle. If that happened first, we want to make sure to apply the fix in that case.
3. The fix itself. @jessegreenberg mentioned lots of stack overflow examples and tests with calling `cancel`, `pause`/`resume`, etc. I would recommend really hashing out all of these, and potentially trying all of them very verbosely. Perhaps `cancel` is needed in some cases, and `pause` in others.

**Comment by jessegreenberg** [comment]
OK the behavior seems a bit better after changes in https://github.com/phetsims/utterance-queue/issues/66. Here is what I expect now:

When speech fails due to switching tabs or one of the other cases pointed out in https://github.com/phetsims/number-play/issues/138#issuecomment-1036416415, speech will stay broken for ~8 seconds but then start to work again more consistently.

**Comment by jessegreenberg** [comment]
@Nancy-Salpepi or @stemilymill or @KatieWoe can you please try number-play on ChromeOS again and see if this is any better?

**Comment by Nancy-Salpepi** [comment]
@jessegreenberg things look much better in NP on master! It still takes a couple of clicks to initiate an utterance, but once it starts, it works well. Switching tabs and leaving it open for a while didn't have a negative affect.

**Comment by jessegreenberg** [comment]
Awesome, thanks for checking both of you! I am going to add this to [the ](https://github.com/phetsims/qa/blob/master/documentation/accessibility-bugs.md) and consider this sufficient for now.
