### ISSUE TITLE
Debug version doesn't play

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#179]
For https://github.com/phetsims/qa/issues/822. Seen on Win 11 Chrome.
When trying to play the debug version of the dev test (https://phet-dev.colorado.edu/html/number-play/1.1.0-dev.1/phet/number-play_all_phet_debug.html) does not load. No console error appears other than a 503 error that does not seem to be related.
<img width="959" alt="nodebug" src="https://user-images.githubusercontent.com/41024075/181812376-c77dc0e9-616d-4467-80ba-9c9dfa9df2d0.png">

**Comment by chrisklus** [comment]
Thanks @KatieWoe! Confirmed that the 1.1.0-dev.1 debug version is not loading for me either on Mac + Chrome. But I just tested the latest dev version (1.1.0-dev.6) and that is working. I'm going to close since at least the last few dev debug versions are starting up for me and will reopen if the next one has issues.
