### ISSUE TITLE
Voicing Notification

### ISSUE THREAD

**Issue by RVieyra** [phetsims/number-play#188]
On translated sims, voices are defaulting to English when no language voice is present on the user's device. This is confusing some of the translators, and is a concern particularly for younger users of the simulation. Two potential fixes:

- @chrisklus Suggested adding a pop-up to let people know when their device's language does not have voicing.
- @jessegreenberg Suggested notifying people how to install more language voices on their devices.

**Comment by jessegreenberg** [comment]
@kathy-phet can you please comment on the priority of this and who you would like to work on it?

**Comment by chrisklus** [comment]
Also - I think it would be good to include this issue for design discussion on Friday

**Comment by amanda-phet** [comment]
@kathy-phet said to @chrisklus that we should work on this, and that we should have a design meeting about it.

**Comment by amanda-phet** [comment]
Met 11/18/22 to discuss this. 

Right now we can reproduce this with `locales=*` so we can test out a solution that we might come up with. 
* AM discovered that Bosnian is likely not on her machine 

This is an issue for primary and secondary locales. 

We'd like a warning that appears when someone sets a language (either the sim-specific secondLocale or the localization tab). However, this would happen while someone is in the middle of using the preferences dialog! Also, a user might still want to change their locales for their sim experience, but the issue is only with the voicing button. 

Big questions: 
**Do we want users to be able to use the voicing button "incorrectly"?** 
* CK thinking the button should probably be disabled for these unavailable locales 
* We'd want it to only be disabled for unavailable locales

**How should we indicate that there is an issue with voicing?** 
* Some kind of messaging about how the sim will work, and instructions on how to download new voices (if applicable) 
* Should we put some kind of notification in the sim? Disable the button? Clicking the button shows a dialog? 
* maybe a warning icon under the button with a tooltip? Or a warning icon on a button that pops up a message? 
* could we indicate the "bad" locales directly in the preferences dialog? could we weird because this would need to be done in joist, and it's a common component for all sims. 
* would be nice to find out all available voices on startup though
* Would be nice to have a pop-up on startup that says "these locales might not voice correctly" - this would probably *always* pop up though. 

**If someone turns on readAloud, but the voice for that locale isn't available, should the sim *not* speak the number?** 
* Since we have the information available when they toggle, could put a message there. 
* If they use the toggle first, then change second locale, they wouldn't see the message. 
* Could add a warning in the preferences dialog in three places that would appear as soon as an unsupported locale is selected- on the Simulation tab, Audio tab under read aloud, and the Localization tab. And in a fourth place, on the sim screen near the audio button. (would either say that the locale won't work, or that it won't work correctly). Maybe it's only needed in two places- in the sim and in the Audio tab. 
* Should we do a pop-up as soon as they close the preferences dialog? AM: this seems like an annoying user experience. 

Decision:
* Put an error message in the Audio tab under the "Hear Total" toggle when we know a locale isn't available for voicing https://fontawesome.com/icons/triangle-exclamation?s=solid&f=classic
* Put an error message in the sim as a button under the voicing button, and disable the voicing button

Messaging: 
Audio tab and sim screen button message: 

> There is no voice found on this device for the selected language(s). 
> 
> Your device may support downloading an additional voice for your language.

**Comment by chrisklus** [comment]
Marking this to review with @amanda-phet during our check in tomorrow.
