### ISSUE TITLE
When "zero" is heard while switching screens varies

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#217]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.2.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/925, with "Hear Total" on, if the value is zero on one/both the 10 and 20 screens, sometimes I hear "zero" when switching screens and sometimes I don't. 

**Steps to reproduce**
Scenario 1:
1. While on the Ten screen, go to the Audio Tab of Preferences Dialog and turn on "Hear Total" (zero is heard) and exit.
2. Click on Twenty screen--nothing is heard
3. Click on Ten screen and add a one to the play area
4. Click on Twenty screen--zero is heard

Scenario 2:
1. Turn on "Hear Total"
2. Go to the Ten screen and add objects to play area
3. Press Reset All --zero is heard
4. Click back and forth between the first 2 screens --nothing is heard on either screen
5. Click back and forth between screen 3 or 4 and screen 1 or 2 --zero is heard

**Visuals**

https://user-images.githubusercontent.com/87318828/229915809-8cab4337-21b6-4615-8196-ade480759c1a.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.1.0-dev.10/phet/number-play_all_phet.html
Version: 1.1.0-dev.10 2023-03-30 22:43:33 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Language: en-US
Window: 1254x705
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! The reason for this behavior is that if the "data" doesn't change when the screen changes, it doesn't speak an update when you enter a screen. So if you enter a screen that has a different number than the screen where you came from, it speaks as to say the starting state is different than the screen where you came from. In the case of the Game or Lab screen, there is no data, which is still treated as different than a screen that has a number.

From a model perspective, this makes sense to me - like, why repeat something that hasn't changed? We know that the language hasn't changed either, so it is guaranteed to be repeating the same speech. But, from a user standpoint i could see how this could be weird since it seems like it's expected to speak when the screen changes.

I think I have a preference for always speaking when the screen changes. This will likely not be an easy change based on the current implementation, though.  @Nancy-Salpepi @zepumph @amanda-phet any more opinions on the behavior?

**Comment by chrisklus** [comment]
@zepumph @amanda-phet and I discussed today and decided that we would always like to hear speech when changing screens (if going to a screen with speech synthesis) and when reset is pressed (all when "Hear..." is turned on). @zepumph and I committed those changes above.

@Nancy-Salpepi can you please test Number Play and Number Compare on phettest for these changes? Thanks!

**Comment by Nancy-Salpepi** [comment]
Changes sound good in both Number Play and Number Compare when changing screens and pressing reset all. Closing!
