### ISSUE TITLE
Oddities when voicing Korean translation

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#218]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/925
When in the Korean translation of the sim the word versions of a number appear in English. However, they are read out as something else. I thought at first it was still the Korean translation of the number even though it doesn't look translated, but the words don't sound like the Korean numbers either.
**Steps to reproduce**
1. Go to the Korean (ko) locale and make sure there is a voice for it
2. Go to the first screen and add some number of objects
3. Open the word box and observe that it appears to be English
4. Press the voicing button

**Visuals**

https://user-images.githubusercontent.com/41024075/230219948-8898b7b3-2ec0-4255-a8a2-2ca05cccdef8.MOV

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪게임 횟수‬
URL: https://phet-dev.colorado.edu/html/number-play/1.1.0-dev.10/phet/number-play_all_phet.html?dev
Version: 1.1.0-dev.10 2023-03-30 22:43:33 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by zepumph** [comment]
@stemilymill and I looked through all babel strings, and it looks like `ko` (Korean) Number Play has translated "one" into "1", and we found another one, for the scenery-phet strings, `vi` (Vietnamese) also had translated the words into numbers. If we need to come up with a general solution for this, let's handle that case too

**Comment by zepumph** [comment]
A couple of things here that made for a really cool issue. 

1. We realized that a gotcha (that was always going to be fixed anyways) over in https://github.com/phetsims/number-suite-common/issues/27 was causing the english words to show up in the WordAccordionBox for korean even though we have a korean translation (the translation is is number-play and not yet copied over to number-suite-common where the string now lives).
2. We found a bug where the spoken item was always the number (coming from the model) instead of whatever word should be spoken. That is why we heard the korean number, because the voice new how to say "1" in korean.
3. We used the knowledge in (2) to create a new issue where the "test voice" ("one two three") should be changed to "1 2 3" so even untranslated strings will hear that in their own language. (new issue to be linked soon).
4. It was such a red herring that it just so happened that `ko` had a translation of the "zero" word to "1". That confused us for quite some time. 

@chrisklus will commit a fix, but there really isn't anything to confirm because we aren't going to update the new strings until just before publication of Number Play (ensuring that korean translations of the number words are transferred).

**Comment by chrisklus** [comment]
Thanks for this issue @KatieWoe! I committed a fix for (2) above. @KatieWoe you should hear the english numbers now pronounced with a Korean voice. Could you please confirm on phettest? Thanks! Feel free to close if behaving as expected.

**Comment by KatieWoe** [comment]
Looks good on phettest
