### ISSUE TITLE
Translator punctuation errors

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#226]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/929, the "Word" box on the Ten and Twenty screens has punctuation issues with some translations.

- French: missing closing parenthesis 

<img width="361" alt="Screenshot 2023-04-03 at 9 10 39 PM" src="https://user-images.githubusercontent.com/87318828/230942051-28c06bc9-64e8-4834-a977-1fd75110d19c.png">

- Hausa: missing parenthesis
<img width="424" alt="Screenshot 2023-04-08 at 3 24 39 PM" src="https://user-images.githubusercontent.com/87318828/230942227-d8e77216-8205-43d8-ae86-8cca51174386.png">

- Dansk: closing parenthesis replaced with curly bracket
<img width="424" alt="Screenshot 2023-04-08 at 3 25 44 PM" src="https://user-images.githubusercontent.com/87318828/230942391-dd2538b5-8e54-4f12-8946-8b347951dcd8.png">

**Comment by chrisklus** [comment]
From 4/11 standup with @zepumph and @Nancy-Salpepi:

We are at least curious to check in with @jbphet to see if we can make some edits in babel to make these a bit better. We will spend 10 minutes on a patch.

**Comment by zepumph** [comment]
Just a note here that we want to make sure to change the number-play strings, and not the number-suite-common strings, because we will blow away those strings over in https://github.com/phetsims/number-suite-common/issues/27.

**Comment by chrisklus** [comment]
@jbphet gave the all good here and pointed me to https://github.com/phetsims/rosetta/blob/master/doc/admin-guide.md#triggering-a-rebuild-without-being-credited in case we ever need to do something like this after publication.

In the above commits I fixed French and Dansk because they were pretty clearly typos and were intending to use parenthesis.

I didn't feel confident enough to change Hausa because they didn't include any parenthesis (or a space). I did some googling and also asked ChatGPT about the use of parenthesis in the language. The best I could find what that they aren't very common and the examples that I saw used them in the way English uses them when someone is saying "in other words", like repeating the same thing that was just said for clarification or translation. So if that is true, I could understand how using parenthesis would be wrong here. Maybe smashing the two words together is the closest thing to saying "Word, but in Italian". This is all speculation, but I'm just trying to say that I don't feel knowledgeable enough to change the translation. Id anyone disagrees, please comment! We can add another patch in the next RC.

I tested Dansk and French on phettest and they are looking great, marking ready to cherry-pick

**Comment by chrisklus** [comment]
Or wait, babel isn't a dependency lol. I'll leave open for a bit if anyone else wants to comment and then close.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2. Closing
