### ISSUE TITLE
Numbers lost when resizing window

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#228]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/929. May be related to https://github.com/phetsims/number-play/issues/223.
When resizing the lab screen the objects from the bottom of the screen and the operator cards stay on the screen, but the numbers from the top carrousel can be lost off screen.
**Steps to reproduce**
1. Go to the lab screen
2. Resize the window to be long and short
3. Place objects on the far end of the screen, including a number card from the carrousel
4. Resize the window close to the standard size

**Visuals**
Before resize:
![beforeresize](https://user-images.githubusercontent.com/41024075/230969305-4a1157a5-a65d-4359-8aba-03eaaebd4ec8.png)
After resize:
![afterresize](https://user-images.githubusercontent.com/41024075/230969337-396c9b5f-71ee-4de4-bcd4-4f9fc6fd675f.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.1.0-rc.1/phet/number-play_all_phet.html
Version: 1.1.0-rc.1 2023-04-07 16:57:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Thanks @KatieWoe!

Let's call the number cards being able to off screen as problem 1.
I noticed problem 2 is that the bounds for constraining the symbols were incorrect. You'll notice this on rc.1 if you do the same test as in your video but along the bottom instead of the left side. The symbols were able to go over the countingObject panels (which they are not able to do when dragging).

Problem 1 and 2 should be fixed from the above commit. Please test this fix by doing the same test as in your video but on all four sides of the screen view. The only thing that should be able to go to the edge of the screen instead of the edge of the panel/carousel is the thing that matches what the panel contains. In other words, this window size change should move things in a way that matches where they are allowed to go when dragging. It is not a problem that the thing doesn't return when it's pushed over the panel.

Noting that when testing you may notice problem 3, which I opened a side issue for (https://github.com/phetsims/number-suite-common/issues/69).

Thanks! Please assign back to me if all good or if more work is needed.

**Comment by KatieWoe** [comment]
Both problem 1 and 2 look good on master

**Comment by chrisklus** [comment]
Thanks @KatieWoe!

**Comment by chrisklus** [comment]
Patche applied above

**Comment by zepumph** [comment]
For QA: Feel free to close if all is good, please note that @Nancy-Salpepi reported yesterday that there is still some strangeness with a card being placed in the top right, and then resize putting it onto the card-creator carousel as a resize occurs. We have determined this is totally fine. Let us know if you run into trouble!

**Comment by veillette** [comment]
Using https://phet-dev.colorado.edu/html/number-play/1.1.0-rc.2/phet/number-play_all_phet.html, (https://github.com/phetsims/qa/issues/932), the dragBounds worked correctly for me but I'll let someone else from QA confirm and close.

**Comment by Nancy-Salpepi** [comment]
This also looks good to me! Closing.
