### ISSUE TITLE
Ones bucket needs a more realistic decrease

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#23]
Currently, the dogs show 3 in the bucket until the total is greater than 7. Then they decrease down to 2, then 1, then none. 

The ones show 2 in the bucket until the total is 10. So even with there is only 1 one available, it looks like there are 2. 

![image](https://user-images.githubusercontent.com/7852916/125835824-db0a468c-2454-4e09-980b-4c3764b215c1.png)

Eventually we'll want to get this sorted out!

**Comment by chrisklus** [comment]
In the above commits I created CountingCreatorNode, which is now used in ExplorePanel from make-a-ten and replaced OnesCreatorNode in number-play. OnesCreatorNode was originally duplicating lots of code from ExplorePanel. I also generalized it to support the display of ones or play objects, and added support for removing one of the two object representations when the sum is 1 away from being the total.

Unfortunately, because of the nature of how we are counting the total, the representation in the bucket does not line up with the animations of the returning numbers. For example, if there are 9 numbers out on the 10 screen, and the total is decreased to 8, the bucket immediately shows 2 numbers again (before the 9th number has returned to the bucket) because we don't consider animating numbers as part of the total. So, as soon as the total goes down to 8, the animating number is not part of the play area (essentially having a value of 0), and the bucket shows 2 numbers again. I'm going to close this issue and handle this remaining aspect over in https://github.com/phetsims/number-play/issues/50
