### ISSUE TITLE
Make a query parameter for counting along

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#35]
@kathy-phet requested a query parameter for using speech synthesis to read out the number as the user interacts. For example, when they make 3, it reads out "three" and as soon as they make 4, it reads out "four", without explicitly pressing the speech button. 

@kathy-phet - do you also want this on the Compare screen? I think that seems like a long sentence to read out, and only thought we'd have this on the Ten and Twenty screens.

**Comment by kathy-phet** [comment]
Yes, I agree. Let's just do it for the first 2 screens.

**Comment by chrisklus** [comment]
Added above. For now, the query parameter is a flag named `countAloud`. @amanda-phet and I also considered `countAloud` and we're open to other suggestions. Labeling for design meeting 1/27.

One thought: we might want to consider adding a small delay so that rapid changing of the current number doesn't play the very beginning of the number multiple times before reading out a full number.

**Comment by chrisklus** [comment]
We reviewed this in design meeting and think it's good to go. 

During design meeting, we did notice there was a 1 or 2 second delay for the first expected sound to play, so I reached out to @jbphet to ask. (I've noticed this happening occasionally, not specific to this feature. I think it is related to just voicing, though). He said that a delay of that long should not be happening - it should be more like 1-200 ms. I'll keep an eye out for this and make an issue if I can figure out to reproduce it.
