### ISSUE TITLE
Max Width of strings should be looked at

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#47]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/696. The max width for a number of strings are either too short or too long.

**Visuals**
<img width="960" alt="longmaxwidth" src="https://user-images.githubusercontent.com/41024075/129950837-83a8253a-560a-4689-a2a0-de3fd3ce8512.png">
<img width="753" alt="shortmaxwidth" src="https://user-images.githubusercontent.com/41024075/129950838-dfc3f5f1-eec0-4ffe-bed6-f2c0e90b25d5.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.22/phet/number-play_en_phet.html?screens=1,2,3&stringTest=long
Version: 1.0.0-dev.22 2021-08-06 03:14:48 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
Language: en-US
Window: 1280x657
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Thanks for bringing this to my attention @KatieWoe, this turned out to be a pretty finicky issue that required some additional structure changes to fix correctly.

Please test on phettest to confirm the strings all scale appropriately - another thing to pay close attention to is the size of the accordion boxes. As soon as the content of an accordion box is wider than its inner width, the whole thing shrinks vertically (like what's in your screenshot). So please double check my maxWidths by having a normal string copy of the sim open in a tab and use that as a reference against the `stringTest=long` sim in a different tab and confirm that the accordion boxes are all matching in size and position.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by chrisklus** [comment]
Awesome, thanks much! Closing.
