### ISSUE TITLE
TypeScript questions

### ISSUE THREAD

**Issue by Luisav1** [phetsims/number-play#81]
From #75 
>Are there any `TODO` or `FIXME` or `REVIEW` comments in the code?  They should be addressed or promoted to GitHub issues.

* If levels include two types of levels, how do we only call resetStartSequence() on the type that has it?
```js
// Transition between the levelSelectionNode and the selected level when the model changes.
    // if levelProperty has a null value, then no level is selected and levelSelectionNode will be displayed.
    model.levelProperty.lazyLink( level => {
      this.interruptSubtreeInput();

      if ( level ) {
        // @ts-ignore TODO-TS
        level.subitizer && level.subitizer.resetStartSequence();

        // Transition to the selected level.
        const selectedLevelNode = _.find( this.levelNodes, levelNode => ( levelNode.level === level ) );
        // @ts-ignore
        transitionNode.slideLeftTo( selectedLevelNode, TRANSITION_OPTIONS );
      }
      else {

        // Selected level was null, so transition to levelSelectionNode.
        transitionNode.slideRightTo( levelSelectionNode, TRANSITION_OPTIONS );
      }
    } );
```

* The newChallenge() function is in an abstract class and should only be called from it's sub-classes but TypeScript isn't letting us declare it as protected because the abstract view type NumberPlayGameLevelNode.ts calls level.newChallenge(), even though that is actually calling sub-class implementations (which are marked as public). Should this be allowed, or is it due to them needing the same signature, or is TypeScript confused?
```js
abstract class NumberPlayGameLevel { ... }
...
 /**
   * Sets up a new challenge for this level.
   */
  public newChallenge(): void { // TODO-TS: why can't this be protected if i only want sub-class implementations to call it?
    this.isChallengeSolvedProperty.value = false;
    this.setRandomChallengeNumber();
    this.numberOfAnswerButtonPressesProperty.reset();
  }
```

* ChallengeNumberProperty is only set in NumberPlayGameLevel.ts, so the public version of it should be IReadOnlyProperty<number> but we rely on reading the range which is not a part of IReadOnlyProperty, so TypeScript errors on those cases. Perhaps we could make a IReadOnlyNumberProperty that adds range to it.

**Comment by marlitas** [comment]
> The newChallenge() function is in an abstract class and should only be called from it's sub-classes but TypeScript isn't letting us declare it as protected because the abstract view type NumberPlayGameLevelNode.ts calls level.newChallenge(), even though that is actually calling sub-class implementations (which are marked as public). Should this be allowed, or is it due to them needing the same signature, or is TypeScript confused?

@Luisav1  - Since `this.level` in NumberPlayGameLevelNode is a generic that extends NumberPlayGameLevel, all that typescript knows for sure is that newChallenge() is protected. Typescript has no knowledge that a subclass may override that, and for all intents and purposes we would be allowed to pass through a subclass that doesn't override it. I think the main question is why do we want it to be protected if all implementations will override the function to be public? It seems unnecessary. 

I am going to leave newChallenge as public and have @pixelzoom confirm wether my thought process is correct or not.

**Comment by pixelzoom** [comment]
Self-assigning to have a look.

**Comment by pixelzoom** [comment]
Making Challenge `newChallenge` public is indeed the correct approach.  It's impossible for the Challenge base class to be instantiated directly, because it's `abstract` and its constructor is `protected`.  And any subclass of Challenge has its `newChallenge` method called in NumberPlayGameScreenView:

```
82       selectedLevelNode.newChallenge();
```

Back to @marlitas in case there's more work to be done here for the other 2 bullets in https://github.com/phetsims/number-play/issues/81#issue-1078803549.

**Comment by marlitas** [comment]
Thanks @pixelzoom!

> ChallengeNumberProperty is only set in NumberPlayGameLevel.ts, so the public version of it should be IReadOnlyProperty but we rely on reading the range which is not a part of IReadOnlyProperty, so TypeScript errors on those cases. Perhaps we could make a IReadOnlyNumberProperty that adds range to it.

@zepumph and I looked at this and it makes sense to keep ChallengeNumberProperty as a NumberProperty for the public API since we need range as well as other NumberProperty behaviors in it's usage. However, we were able to clean up some downstream usages of NumberProperty, and will continue doing typescript cleanup work in that vein here: https://github.com/phetsims/number-play/issues/177

> If levels include two types of levels, how do we only call resetStartSequence() on the type that has it?

Looks like this was addressed in https://github.com/phetsims/number-play/commit/23c80b1486dfe8f61b08f7cca4569b42c84cee2b

closing as completed.
