### ISSUE TITLE
Subitize level-selection buttons look wrong with stringTest.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#89]
For #84 

With `stringTest=long` or even `stringTest=X`, the level-section buttons for the Counting game levels (top row of buttons) look totally wrong. They look like Subitize buttons:

<img width="988" alt="screenshot_1457" src="https://user-images.githubusercontent.com/3046552/146097580-f4f4faf1-6ed2-4fa4-96ee-717cd21ebce7.png">

Compare to without `stringTest`:

<img width="985" alt="screenshot_1458" src="https://user-images.githubusercontent.com/3046552/146097780-97cc9ca5-6a85-47b0-a904-eb7f5574d2ee.png">

**Comment by chrisklus** [comment]
Oops, @Luisav1 we made the mistake of using a translated string as a key for the instead of creating an enum for this purpose

**Comment by Luisav1** [comment]
@chrisklus and I think the way we fix this depends on how we redo the gameLevels. If we keep the 'a' and 'b' pattern, then we can use the constants here, otherwise an enum would be created.

**Comment by Luisav1** [comment]
@chrisklus and I also worked on this but ran into an issue using enums as the key to a map for the level images so we're wondering if this might be a place to use rich enumerations instead.

**Comment by chrisklus** [comment]
In the above commit, @Luisav1 and I converted the model to have an enumeration value as its game type. This game type is then used in maps to get the game type name and button image for each game type + level combo. Since this pattern feels like we are just making a fake rich enumeration and there are various lint problems with the syntax for both defining the type with an enum in it and using an enum value as a key in an object (value appears as a string, which lint flags as `dot-notation` error), we should likely convert both of these maps to one rich enumeration that is defined in the game section of the NumberPlayConstants file. However, that file is not yet in typescript and it looks like rich enumerations are not finalized for TS over in https://github.com/phetsims/chipper/issues/1106.

That said, this was an improvement and the problem described in the initial comment of this issue has been fixed. Closing.
